=head1 NAME

CPAN Mangler

=head1 DESCRIPTION

Subvert CPAN to your will

=head1 SYNOPSIS

    plackup cpan-mangler/app.psgi
    # Twiggy: Accepting connections at http://0.0.0.0:5000/

Point your favourite graphical web browser at this URL and your CPAN code
snippets will now enjoy syntax highlighting.

=head1 INSTALLATION

    git clone http://github.com/oalders/cpan-mangler.git

    cpanm Plack Plack::App::Proxy Plack::Handler::Twiggy Plack::Middleware::HTMLify HTML::Highlighter

    cd cpan-mangler
    plackup

=head1 ACKNOWLEDGEMENTS

We'd like to thank the following people for their contributions:

Jesse Thompson
    The search dependents data is a slight reworking of Jesse's
    excellent Greasemonkey script:
    L<http://blogs.perl.org/users/jesse_thompson/2010/08/cpan-search-dependents.html>

Lee Aylward
    Lee added HTML::Highlighter integration: L<http://github.com/leedo>

Our cross-domain AJAX requests were inspired by this tutorial:
L<http://blancer.com/tutorials/14841/quick-tip-cross-domain-ajax-request-with-yql-and-jquery/>
