=head1 NAME

CPAN Mangler

=head1 DESCRIPTION

Subvert CPAN to your will

=head1 SYNOPSIS

    plackup cpan-mangler/app.psgi
    # Twiggy: Accepting connections at http://0.0.0.0:5000/

Point your favourite graphical web browser at this URL and your CPAN code
snippets will now enjoy syntax highlighting.

=head1 INSTALLATION

    git clone http://github.com/oalders/cpan-mangler.git

    cpanm Plack Plack::App::Proxy Plack::Handler::Twiggy Plack::Middleware::HTMLify HTML::Highlighter

    cd cpan-mangler
    plackup
